name: Stock Alert Workflow

on:
  workflow_dispatch: # Esto permite ejecutar el workflow manualmente desde la interfaz de GitHub

jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run the stock alert script
        run: |
          python src/main.py

